### PR TITLE
Add Dummy Project

### LINKED ISSUE #38: script to generate _godot_defs
https://github.com/johnfn/ts2gd/commit/c31b2aab83c6a23ed646fba30c06a78dda9c20f8 had some changes related to the _godot_defs, but the changed defs weren't included.
Trying to generate these to fix, I ran into the situation of this repo not having some ts2gd.json to run on for generation of these.
Should we include a small godot project, so that we can run the command?

### PR DESCRIPTION
**Pull request by ksjogo**
Adding a dummy project to be able to generate type definitions.
Added godot 3.x branch as a submodule to have a deterministic source for types.
Closes #38

### CODE REVIEW

**Comment by johnfn** [comment]
I think a lot of the difference is cuz my Prettier removes semicolons from lines by default: https://github.com/johnfn/ts2gd/blob/main/package.json#L30

Can you make sure you're using that config? Other than that, this is a fantastic change!

**Comment by ksjogo** [comment]
I don't see any prettier stuff.
I think it is mostly new comments from the 3.4 branch being added to the typedefs?

Will add lint-staged with prettier to make that easier as well though.

**Comment by johnfn** [comment]
Oh, you're totally right. I looked a little too fast and I saw that the .d.ts files had semicolons. :) Anyway if you can fix up the merge conflicts here we should be good to go!

**Comment by ksjogo** [comment]
Sure, did rebase.

**Comment by johnfn** [comment]
Thanks!

**Pull request merged**
