### PR TITLE
add tests on CI

### PR DESCRIPTION
**Pull request by ksjogo**
Should show checkmarks for passed tests on PRs now.

### CODE REVIEW

**Comment by ksjogo** [comment]
Example of checkmarks:
https://github.com/KronbergerSpiele/ts2gd/pull/1
https://github.com/KronbergerSpiele/ts2gd/runs/4275877008?check_suite_focus=true
I think they will only be enabled here after merge, so no one can just run stuff with the repo secrets potentially.

**Comment by johnfn** [comment]
This is awesome! Would you mind fixing the merge conflicts - then I can merge it.

**Comment by ksjogo** [comment]
Sure, updated.

**Comment by johnfn** [comment]
Awesome, thanks so much!

**Pull request merged**
