### PR TITLE
don't error on creation of existing directories 

### PR DESCRIPTION
**Pull request by ksjogo**
and don't overwrite launch.json if it exists

### CODE REVIEW

**Comment by johnfn** [comment]
Thanks, appreciate it! 

BTW, if you need any help with setting up ts2gd or tracking down bugs, feel free to add me on Discord: johnfn#0001. It's a hobby project for me, but it works pretty well in my personal use, but then again, I know all the edge cases.

**Comment by ksjogo** [comment]
Hey Grant, they discord link doesn't seem to work/points to issue number one. Happy to ask you there.
Currently looking into running ts2gd with a personal project which currently was using some F# as scripting language. But that was very cumbersome and didn't gain that much (plus mono things being annoying to set-up), so trying to switch to normal Godot + Scripts. 
ts2gd seems very interesting in the sense that the runtime stays untouched and will be able to go with further Godot versiosn relatively easily where as with an embedded JS runtime that doesn't seem to be the case.

One thing I ran into was that there doesn't seem to be a non-interactive build step. I have CI setup for my Godot projects and would kind of need that. 
But doesn't seem to complicated to add this here, so might give it a try.

**Comment by johnfn** [comment]
Oops, that's weird. Here's a second try for my discord: `johnfn#1` 

Good point about the non-interactive build step! That should be pretty easy since running `ts2gd` does a full build immediately when you run it, so it should be as simple as just `if (flag) exit()` after that's done. (Or maybe that should be the default, and --watch should be what it does now!) 

Yeah, I hope it can be useful! It's basically just as lightweight as writing GDScript - a lot easier than embedding a JS runtime into your game!

**Comment by johnfn** [comment]
Just added `--buildOnly`: https://github.com/johnfn/ts2gd/commit/4351aeac52c2d36917fbeac517edf56a228b9b31

**Pull request merged**
