### PR TITLE
remove js files from repo and automate publishing

### PR DESCRIPTION
**Pull request by ksjogo**
This is removing the js files from version and control and automating the publishing of new version to npm.
You will need to add the NPM_TOKEN to the repo's secrets before merging to have it work.

### CODE REVIEW

**Comment by ksjogo** [comment]
Run at https://github.com/KronbergerSpiele/ts2gd/runs/4293009113?check_suite_focus=true
It will not publish if the version number isn't bumped

**Comment by johnfn** [comment]
This is fantastic, thanks for helping clean up the repo :) Of course I caused some merge conflicts but when you fix those up I'm happy to merge this.

**Comment by ksjogo** [comment]
Sure, rebased.

**Comment by johnfn** [comment]
Thanks!

**Pull request merged**
